version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: apache2_php
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
